apiVersion: autoscaling/v1
kind: HorizontalPodAutoScalar
metadata:
  name: nginx
spec:
  minReplicas: 1
  maxReplicas: 5
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: nginx
  targetCPUUtilizationPercentage: 20

