apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: shopping-api
  namespace: shopping
rules:
  - apiGroups:
      - ""
    resources:
      - "pods"
    verbs:
      - "get"
      - "watch"
      - "list"
