apiVersion: v1
kind: Deployment
metadata:
  name: nginx
  namespace:  quota-demo-ns 
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    containers:
      name: nginx
      image: nginx
      resources:
        limits:
          memory: 128Mi # Required in a namespace with resources quota (memory & cpu) set 
                        # The other way around tho is to create LimitRange.

