apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-singed-cert
  namespace: cert-manager-test
spec:
  dnsNames:
    - example.com
  issuerRef:
    name: test-self-signed
  secretName: self-signed-cert-tls
